language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

cache:
  - pip

before_install:
  - travis_retry sudo apt-get install -y inkscape

install:
  - travis_retry pip install -q cython numpy
  - pip install -e .
  - python -c 'import cortex; print(cortex.__full_version__)'

script:
  # install necessary packages to run tests and run tests
  - travis_retry pip install -q -U pytest pytest-cov codecov
  - pytest --cov=./
  # test installation
  - python setup.py install
  # install packages for docs and make docs
  - travis_retry pip install -q ipython Sphinx sphinx-gallery numpydoc
  - cd docs && make html && cd ..
  # Tell GitHub not to use jekyll to compile the docs
  - touch docs/_build/html/.nojekyll

after_success:
  - codecov

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    on:
      branch: master
      tags: true
      # push only once
      python: "3.7"
    local_dir: docs/_build/html/

  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: master
      # push only once
      python: "3.7"
    local_dir: docs/_build/html/
    repo: pycortex/pycortex.github.io
    target_branch: master

  - provider: pypi
    user: "__token__"
    password: $PIPY_TOKEN
    on:
      distributions: sdist
      tags: true
      branch: master
      repo: gallantlab/pycortex
      python: "3.7"